# Makefile.Host
TOP = ../../..
include $(TOP)/config/CONFIG_APP
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (default: NO)
#DB_OPT = YES

#----------------------------------------------------
#  Optimization needs the name of the appropriate
#  dbd file (compare with ../src/Makefile.Vx)
#DBDNAME = exampleApp.dbd

#----------------------------------------------------
# Add databases, templates, substitutions like this

DB += ai.db
DB += ana.db
DB += ao.db
DB += bi.db
DB += bin.db
DB += bo.db
DB += mbbi.db
DB += mbbo.db
DB += ramp.db
DB += eip_stat.db 
DB += test.db 

#----------------------------------------------------
# Declare template files which do not show up in DB
#USES_TEMPLATE += dbExample2.template

#----------------------------------------------------
# The following line is for local dbd expansion
#DBDEXPAND = ether_ip_Include.dbd

include $(TOP)/config/RULES.Db
#----------------------------------------
#  ADD RULES AFTER THIS LINE
