# Makefile.Host
TOP = ../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Add databases, templates, substitutions like this

DB += ai.db
DB += ana.db
DB += ao.db
DB += bi.db
DB += bin.db
DB += bo.db
DB += mbbi.db
DB += mbbo.db
DB += ramp.db
DB += eip_stat.db
DB += test.db
DB += mod.db
DB += brad.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
