#
# Makefile.Host,v 1.1.2.2 1999/07/30 21:16:06 lange Exp
#

TOP=../..
include $(TOP)/config/CONFIG_APP

TARGETS = CONFIG_APP_INCLUDE

include $(TOP)/config/RULES.Host

inc:: $(TARGETS)

ifeq ($(wildcard $(TOP)/config/RELEASE.$(HOST_ARCH)),$(TOP)/config/RELEASE.$(HOST_ARCH))
CONFIG_APP_INCLUDE: $(TOP)/config/RELEASE.$(HOST_ARCH)
endif

CONFIG_APP_INCLUDE: $(TOP)/config/RELEASE $(TOP)/config/CONFIG_APP
	$(RM) $@
	@$(PERL) $(TOP)/config/makeConfigAppInclude.pl $(T_A) $@ $(TOP)
